### ISSUE TITLE
Decide on Venue

### ISSUE THREAD

**Issue by marcusramberg** [oslo-pm/NPW2018#1]
Find a suitable place in the Oslo region with room for ~100 - MET seems like a promising lead.

**Comment by marcusramberg** [comment]
MET Might be an issue with weekdays, @geira does a discovery,
and also checks forskingsparken.
Other alternatives: 
* Teknologihuset. @krunen 
* Aktivitetshuset K1 Tøyet. @nicomen 

Please report back in this issue when you have more info.

**Comment by geira** [comment]
On 09/18/2017 06:42 PM, Marcus Ramberg wrote:
> Assigned #1 to @geira.

Vennligst bruk min private konto til dette, ikke jobbadressen.

-geir

**Comment by nicomen** [comment]
@sjn tar teknologihuset

**Comment by marcusramberg** [comment]
Vi har fortsatt ikke fått et endelig pristilbud fra Teknologihuset, Salve håper avklaring neste uke. @geira hvis det går greit vil vi gjerne avvente endelig avgjørelse på venue til det er inne.

**Comment by arnesom** [comment]
Det blir Teknologihuset. Da kan denne lukkes.

**Comment by arnesom** [comment]
Kan noen legge inn teksten fra Teknologihuset, så vi har dokumentasjon på dato og pris?

**Comment by marcusramberg** [comment]
Så vidt jeg forsto ble denne avtalen gjort muntlig av @krunen . Gir den til ham så han kan bekrefte og lukke denne saken.

**Comment by krunen** [comment]
Her er tilbudet jeg takket ja til, for 6. og 7. september:

> Hei Karl, da har jeg sjekket i forhold til leiepris. 
> 
> Vi kan gi dere rabatt på lokalleie til konferansen og 20.000,- for 2 dager er ok :-)
> 
> Vil dere da beholde bookingen?
> 
> Mvh,
> Cathrine Opheim
> Event Manager, Teknologihuset
> Macsimum Event
> Teknologihuset, Pilestredet 56, 0167 Oslo
> Mob: 92249431
>

**Comment by sjn** [comment]
Er dette inkludert MVA?

**Comment by geira** [comment]
Har dere gitt beskjed til Forskningsparken som vel fortsatt har reservert
lokalene for dere?

Ellers kan jeg vel med fordel tas bort fra mailinglista siden jeg ikke
lenger sitter i styret.

-geir
