### ISSUE TITLE
As a developer, I want to make sure the Act instance is working before I push it to production

### ISSUE THREAD

**Issue by jhthorsen** [oslo-pm/NPW2018#11]
I've created an issue regarding setting up act in #10. This issue is about testing the changes made in that issue.

What needs testing:

- [x] Check that you can create a new user
- [x] Check that you can login
- [x] Check that you can get a new password using "Forgotten Password"
- [x] Check that you can submit a talk
- [x] Report any other bug you can find
- [x] Check that https://github.com/Act-Conferences/npw2018/blob/master/actdocs/conf/act.ini has the correct setup

...and anything else that looks strange/needs fixing.

The test instance is located at http://test.mongueurs.net/npw2018/main - This is just a test site, so you can register/unregister/do whatever you want, and it won't affect anything.

Please report any issues here or ask in #oslo.pm on irc.perl.org if you have any questions.

Note that http://test.mongueurs.net/npw2018/ will redirect you to http://oslo.pm/npw2018/, which is intended.

**Comment by krunen** [comment]
Tried to register, but I haven't received the confirmation email after 10 minutes.

**Comment by marcusramberg** [comment]
Same. Tried 3 times, no mail. :(

***
Marcus Ramberg
+47 94 35 77 47
http://marcus.nordaaker.com <http://nordaaker.com>

**Comment by jhthorsen** [comment]
> maddingue: just realized the error.log had once again filled the disk. sorry, should have seen that earlier

You can try to register again now.

**Comment by krunen** [comment]
It worked now.
I have registered, changed forgotten password, and submitted a talk. This works fine.
I can't find where to register to the conference. Is that because I have submitted a talk?

**Comment by tyldum** [comment]
Seems you are registered once you create the account.
And once you leave http://test.mongueurs.net/npw2018/main and enter the http://oslo.pm/npw2018/ site, there is no way back to ACT and managing yourself.

Was able to de-register and re-register.

**Comment by jhthorsen** [comment]
@tyldum: Thanks for testing! This issue with navigation is covered in #10 👍To summarise: Won't add the menu items before we go live.

**Comment by jhthorsen** [comment]
@krunen, @marcusramberg: Got any comments to act.ini? Like https://github.com/Act-Conferences/npw2018/commit/7c7055c6237ff676e109277a8f87d3cdfc118ab9

**Comment by krunen** [comment]
I think act.ini looks good. Would be nice if others could comment on the prices.

**Comment by marcusramberg** [comment]
(I'm fine with those prices too)

**Comment by jhthorsen** [comment]
Awesome! Thanks everybody 👍
