### ISSUE TITLE
Make a great web page for the conference

### ISSUE THREAD

**Issue by marcusramberg** [oslo-pm/NPW2018#3]
* [x] Establish http://oslo.pm/npw2018
* [x] Redirect http://mojoconf.com to ^^
* [x] Redirect http://mojoconf.org to ^^
* [ ] Redirect http://perlworkshop.no & friends to ^^

**Comment by jhthorsen** [comment]
@sjn: Can you redirect http://perlworkshop.no to http://oslo.pm/npw2018/ ?
