### ISSUE TITLE
Ensure we get the word out about the conference.

### ISSUE THREAD

**Issue by marcusramberg** [oslo-pm/NPW2018#4]
TODO:

* [x] https://groups.google.com/forum/#!forum/mojolicious/topics
* [ ] https://www.perl.org/events.html
* [x] Identify interesting groups for marketing

Done:
* [x] http://www.yapceurope.org/events/workshops.html - @jhthorsen has sent email to workshops@yapceurope.org
* [x] Get the call for paper into Perl Weekly - @jhthorsen has sent an email to Gabor
* [x] https://github.com/szabgab/codeandtalk.com/blob/main/docs/EVENTS.md - https://github.com/szabgab/codeandtalk.com/pull/559
* [x] https://twitter.com/mojoconf
* [x] https://www.linkedin.com/feed/ - https://www.linkedin.com/groups/106254
* [x] http://mojolicious.org/
* [x] https://www.meetup.com/Oslo-pm/events/250184644/
* [x] https://www.facebook.com/groups/oslo.pm/permalink/10156337889322812/
* [x] https://www.reddit.com/r/perl/comments/8fqct4/npw_mojoconf_2018_in_oslo_norway_67_sep_submit_a/

**Comment by jhthorsen** [comment]
I don't have the login to @mojoconf on Twitter. Asked in #oslo.pm on IRC. Here is the tweet I want to post:

> #Mojoconf in #Oslo this September! Want to submit a talk or just meet a bunch of awesome #perl programmers? Get more information at http://oslo.pm/npw2018/ #mojolicious

**Comment by jhthorsen** [comment]
@sjn, @krunen, @stigtsp: Upvote on reddit? 👍  https://www.reddit.com/r/perl/comments/8fqct4/npw_mojoconf_2018_in_oslo_norway_67_sep_submit_a/
