### ISSUE TITLE
Find gophers for (pr|t)actical tasks, plan tasks.

### ISSUE THREAD

**Issue by marcusramberg** [oslo-pm/NPW2018#8]
Use the whip, luke.

**Comment by stigtsp** [comment]
Thoughts: 
For 80+ attendees we need 5 crew that can help. 1-2 from org should also be on stand by and help.

Consider: Provide refreshments (bev, coffee, tea)?

Before:
- [ ] Set up (tables, banners, ...)
- ...

During:
- [ ] Welcoming attendees, check badges, give goodiebags
- [ ] Check/fix hygiene (common areas, bathrooms)

After (incl. organizers):
- [ ] Tidy/clean
- ...

**Comment by arnesom** [comment]
(I tried replying by email, but that doesn't work.)

Can we use students as crew, by giving them free entry - and some time off?

**Comment by stigtsp** [comment]
Yes, and maybe peeps from IRC.

**Comment by stigtsp** [comment]
+ Video recording
+ Handling VIPs
