### ISSUE TITLE
Create an email for the conference

### ISSUE THREAD

**Issue by jhthorsen** [oslo-pm/NPW2018#9]
I think we should have a contact email. My suggestion is npw2018@oslo.pm.

Here are the emails we have used in the past:

* mojoconf14@oslo.pm
* mojoconf@oslo.pm
* npw2009-info@perlworkshop.no
* p6hackathon@perlworkshop.no

**Comment by sjn** [comment]
Done. npw2018 at oslo.pm now forwards to

arne at oslo.pm, batman at oslo.pm, geir at oslo.pm, krunen at oslo.pm, marcus at oslo.pm, nicomenat oslo.pm, sjn at oslo.pm

These again forward to each respective private address

**Comment by jhthorsen** [comment]
Cool! I've updated the contact email as well. 90d2252
